services:
  db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: motion_db
      POSTGRES_USER: motion_user
      POSTGRES_PASSWORD: motion_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@motion.com
      PGADMIN_DEFAULT_PASSWORD: motion
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
